# Generated by Django 4.0.4 on 2022-04-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
