# Generated by Django 4.0.4 on 2022-04-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0003_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
