# Generated by Django 4.0.4 on 2022-04-28 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0004_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issued_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('issued_date', models.DateField()),
                ('return_date', models.DateField()),
                ('charge_per_day', models.PositiveIntegerField()),
                ('total_charge', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_admin.book')),
            ],
        ),
    ]
