# Generated by Django 4.0.4 on 2022-04-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0005_issued_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_book',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issued_book',
            name='total_charge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
