# Generated by Django 3.1.4 on 2022-05-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0007_auto_20220509_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issued_book',
            options={'ordering': ['id']},
        ),
    ]
