# Generated by Django 4.0.4 on 2022-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
